name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.WEB_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd content
          npm ci

      - name: Build
        run: |
          cd content
          npm run build

      - name: Debug - List content of public directory
        run: |
          echo "Contents of content/public:"
          ls -R content/public

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r content/public/* deploy/ || echo "No files in content/public"
          cp -r content/public/.* deploy/ 2>/dev/null || echo "No hidden files in content/public"
          cp content/CNAME deploy/ 2>/dev/null || echo "No CNAME file found"
          touch deploy/.nojekyll

      - name: Debug - List content of deploy directory
        run: |
          echo "Contents of deploy directory:"
          ls -R deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          cname: barryw.xyz
          force_orphan: true
          allow_empty_commit: true
          external_repository: GithuBarry/GithuBarry.github.io