name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.WEB_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd private-repo
          npm ci

      - name: Build
        run: |
          cd private-repo
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./private-repo/public
          publish_branch: gh-pages
          cname: barryw.xyz
          force_orphan: true
          allow_empty_commit: true
          external_repository: GithuBarry/GithuBarry.github.io