name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.WEB_PAT }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'
          extended: true

      - name: Build
        run: |
          echo "Hugo Cache Dir: $(hugo config | grep cachedir)"
          cd my-hugo-academic
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./my-hugo-academic/public
          publish_branch: gh-pages
          cname: barryw.xyz
          allow_empty_commit: true
          external_repository: GithuBarry/GithuBarry.github.io
