name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.WEB_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd content
          npm ci

      - name: Build
        run: |
          cd content
          npm run build

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r content/build/* deploy/
          cp -r content/public/* deploy/ 2>/dev/null || :
          cp content/public/.* deploy/ 2>/dev/null || :
          touch deploy/.nojekyll
          # Create a simple index.html file
          echo '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Barry Wang</title><script type="module" src="/build/entry.client-3GCWDQRI.js"></script></head><body><div id="root"></div></body></html>' > deploy/index.html

      - name: Debug - List content of deploy directory
        run: |
          echo "Contents of deploy directory:"
          ls -la deploy
          echo "Contents of deploy/build directory:"
          ls -la deploy/build
          echo "Content of deploy/index.html:"
          cat deploy/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          cname: barryw.xyz
          force_orphan: true
          allow_empty_commit: true
          external_repository: GithuBarry/GithuBarry.github.io