name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.WEB_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd content
          npm ci

      - name: Build
        run: |
          cd content
          npm run build

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r content/build/* deploy/
          cp -r content/public/* deploy/
          cp content/public/.* deploy/ 2>/dev/null || :
          touch deploy/.nojekyll
          # Ensure index.html is in the root
          if [ -f content/public/index.html ]; then
            cp content/public/index.html deploy/
          elif [ -f content/build/index.html ]; then
            cp content/build/index.html deploy/
          else
            echo "Warning: index.html not found in public or build directories"
          fi

      - name: Debug - List content of deploy directory
        run: |
          echo "Contents of deploy directory:"
          ls -la deploy
          echo "Contents of deploy/build directory:"
          ls -la deploy/build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          cname: barryw.xyz
          force_orphan: true
          allow_empty_commit: true
          external_repository: GithuBarry/GithuBarry.github.io