name: GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.WEB_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd content
          npm ci

      - name: Build
        run: |
          cd content
          npm run build

      - name: Prepare deployment
        run: |
          cd content
          mkdir -p deploy
          cp -r public/* deploy/
          cp -r public/.* deploy/ 2>/dev/null || :

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./content/deploy
          publish_branch: gh-pages
          cname: barryw.xyz
          force_orphan: true
          allow_empty_commit: true
          external_repository: GithuBarry/GithuBarry.github.io